version: '3.8'

services:
  astro:
    build: .
    ports:
      - "4321:4321"
    volumes:
      - ./src:/usr/src/app/src
      - ./public:/usr/src/app/public
    environment:
      - CHOKIDAR_USEPOLLING=true
    tty: true